api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('accounts/', views.AccountsList.as_view()),
]

envelopes/urls.py
from django.urls import path

from .views import EnvelopeListView, EnvelopeDetailView, EnvelopeCreateView
from .views import TransactionCreateView, SpendCreateView

urlpatterns = [
    path('<int:pk>/', EnvelopeDetailView.as_view(), name='envelope_detail'),
    path('newspend/', SpendCreateView.as_view(), name='envelope_new_spend'),
    path('newtransaction/', TransactionCreateView.as_view(), name='transaction_new'),
    path('new/', EnvelopeCreateView.as_view(), name='envelope_new'),
    path('', EnvelopeListView.as_view(), name='envelope_list'),
]

expense_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('envelopes/', include('envelopes.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),

    # api urls
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

envelopes/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

class Envelope(models.Model):
    class EnvelopeIcon(models.TextChoices):
        GROCERIES = 'fas fa-shopping-basket', _('Groceries')
        FOODANDDRINKS = 'fas fa-coffee', _('Food and Drinks')
        ENTERTAINMENT = 'fas fa-compact-disc', _('Entertainment')
        FURNITURE = 'fas fa-couch', _('Furniture')
        # CREDITCARD = 'far fa-credit-card', _('Credit Card')
        SPORTS = 'fas fa-dice', _('Sports')
        MEDICINE = 'fas fa-hospital', _('Medicine')
        MOBILE = 'fas fa-mobile-alt', _('Mobile Phone')
        # SAVINGS = 'fas fa-piggy-bank', _('Savings')
        SHOPPING = 'fas fa-store', _('Shopping')
        UTILITIES = 'fas fa-tools', _('Utilities')
        CLOTHES = 'fas fa-tshirt', _('Clothes')
        BABYCARE = 'fas fa-baby-carriage', _('Baby Care')
        BOOKS = 'fas fa-book', _('Books')
        TRANSPORTATION = 'fas fa-bus', _('Transportation')
        GIFTS = 'fas fa-box-open', _('Gifts')
        TRAVEL = 'fas fa-car', _('Travel')
        TOOLS = 'fas fa-hammer', _('Tools')
        INTERNET = 'fas fa-wifi', _('Internet')
        INSURANCE = 'fas fa-car-crash', _('Insurance')
        WATER = 'fas fa-water', _('Water')
        BILLS = 'fas fa-file-invoice', _('Bills')
        FUEL = 'fas fa-gas-pump', _('Fuel')
        ELECTRICITY = 'far fa-lightbulb', _('Electricity')
        MISCELLANEOUS = 'fas fa-cannabis', _('Miscellaneous')
        

    name = models.CharField(max_length=255)
    balance = models.DecimalField(decimal_places=2, max_digits=8, default=0.0)
    description = models.CharField(max_length=255, null=True, blank=True)
    icon = models.CharField(
        max_length=30,
        choices=EnvelopeIcon.choices,
    )
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('envelope_list')

class Spend(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits=8)
    date = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=255, null=True, blank=True)
    envelope = models.ForeignKey(
        Envelope,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('envelope_detail', kwargs={'pk': self.envelope.pk,})

class Transaction(models.Model):
    class TransactionCategory(models.TextChoices):
        INCOME = 'IN', _('Income')
        EXPENSE = 'EX', _('Expense')

    amount = models.DecimalField(decimal_places=2, max_digits=8)
    date = models.DateTimeField(auto_now_add=True)
    category = models.CharField(
        max_length=2,
        choices=TransactionCategory.choices,
    )
    envelope = models.ForeignKey(
        Envelope,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('envelope_detail', kwargs={'pk': self.envelope.pk,})

envelopes/forms.py
from django.forms import ModelForm
from django import forms

from .models import Transaction, Spend

class SpendCreateForm(ModelForm):
    class Meta:
        model = Spend
        fields = '__all__'
        widgets = {
            'envelope': forms.Select(attrs={'class': 'account__new-input'}),
        }

class TransactionCreateForm(ModelForm):
    class Meta:
        model = Transaction
        fields = '__all__'
        widgets = {
            'envelope': forms.Select(attrs={'class': 'px-3 py-3 placeholder-gray-400 text-gray-700 bg-gray-200 rounded text-sm shadow focus:outline-none focus:shadow-outline w-full appearance-none'}),
            'category': forms.Select(attrs={'class': 'px-3 py-3 placeholder-gray-400 text-gray-700 bg-gray-200 rounded text-sm shadow focus:outline-none focus:shadow-outline w-full appearance-none'}),
        }

envelopes/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.db.models import Sum

from .models import Envelope, Transaction, Spend
from .forms import TransactionCreateForm, SpendCreateForm

from accounts.models import TransferToEnvelope, Account

class EnvelopeListView(LoginRequiredMixin, ListView):
    model = Envelope
    template_name = 'envelopes/envelope_list.html'
    login_url = 'login'

    def get_queryset(self):
        return Envelope.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_balance_envelopes'] = Envelope.objects.filter(owner=self.request.user).aggregate(Sum('balance')).get('balance__sum')
        context['all_accounts'] = Account.objects.filter(owner=self.request.user)
        return context 

class EnvelopeDetailView(LoginRequiredMixin, DetailView):
    model = Envelope
    template_name = 'envelopes/envelope_detail.html'
    login_url = 'login'

    def get_queryset(self):
        return Envelope.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['transfers_to_envelopes'] = TransferToEnvelope.objects.filter(envelope=self.kwargs['pk'])
        return context 

class EnvelopeCreateView(LoginRequiredMixin, CreateView):
    model = Envelope
    template_name = 'envelopes/envelope_new.html'
    fields = ['name', 'balance', 'icon', 'description']
    login_url = 'login'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_accounts'] = Account.objects.filter(owner=self.request.user)
        return context

""" ====================================== Spend ====================================== """

class SpendCreateView(LoginRequiredMixin, CreateView):
    model = Spend
    template_name = 'envelopes/envelope_new_spend.html'
    form_class = SpendCreateForm
    login_url = 'login'

    def get_context_data(self, **kwargs):
        context = super(SpendCreateView, self).get_context_data(**kwargs)
        context['form'].fields['envelope'].queryset = Envelope.objects.filter(owner=self.request.user)
        context['all_envelopes'] = Envelope.objects.filter(owner=self.request.user)
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        envelope = Envelope.objects.get(pk=form.instance.envelope.id)
        envelope.balance = form.instance.envelope.balance - form.instance.amount
        envelope.save()
        return super(SpendCreateView, self).form_valid(form)


""" ====================================== Transactions ====================================== """

class TransactionCreateView(LoginRequiredMixin, CreateView):
    model = Transaction
    template_name = 'envelopes/transaction_new.html'
    form_class = TransactionCreateForm
    #fields = ['envelope', 'category', 'amount']
    login_url = 'login'

    def get_context_data(self, **kwargs):
        context = super(TransactionCreateView, self).get_context_data(**kwargs)
        context['form'].fields['envelope'].queryset = Envelope.objects.filter(owner=self.request.user)
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        envelope = Envelope.objects.get(pk=form.instance.envelope.id)
        
        if(form.instance.category == 'IN'):
            envelope.balance = form.instance.envelope.balance + form.instance.amount
        else:
            envelope.balance = form.instance.envelope.balance - form.instance.amount
        envelope.save()
        return super(TransactionCreateView, self).form_valid(form)

templates/envelopes/envelope_detail.html
{% extends 'base.html' %}

{% block title %}Envelope Details{% endblock title %}

{% block style %}{% endblock style %}

{% block content %}

<section class="section">

  <div class="account-detail__container bd-grid">
    <div class="account-detail__card">
      <div class="account-detail__icon-background">
        <i class="{{ envelope.icon }} account-detail__icon"></i>
      </div>
      
      <div class="account-detail__name">{{ envelope.name }}</div>
      <div class="account-detail__balance">{{ envelope.balance }}</div>
      <div class="account-detail__description">{{ envelope.description }}</div>
    </div>
    
    <table class="account-detail__table">
      <thead>
        {% if envelope.spend_set.all|length == 0 %}
          <tr>
            <th class="account-detail__table-title" colspan="3">No Sepnds to display</th>
          </tr>
        {% else %}
          <tr>
            <th class="account-detail__table-title" colspan="3">Spends</th>
          </tr>
          <tr class="account-detail__table-header-row">
            <td class="account-detail__table-header">Amount</td>
            <td class="account-detail__table-header">Date and Time</td>
            <td class="account-detail__table-header">Comment</td>
          </tr>
        </thead>
        <tbody>
          {% for item in envelope.spend_set.all|dictsortreversed:"date" %}
            <tr>          
              <td class="account-detail__table-data">{{ item.amount }}</td>
              <td class="account-detail__table-data">{{ item.date }}</td>       
              <td class="account-detail__table-data">{{ item.comment|truncatechars:12 }}</td>    
            </tr>
          {% endfor %}
        {% endif %}      
    </table>   

    <table class="account-detail__table">
      <thead>
        {% if transfers_to_envelopes|length == 0 %}
          <tr>
            <th class="account-detail__table-title" colspan="3">No Tranfers to Envelopes to display</th>
            
          </tr>
        {% else %}
          <tr>
            <th class="account-detail__table-title" colspan="4">Tranfers from Accounts</th>
          </tr>
          <tr class="account-detail__table-header-row">
            <td class="account-detail__table-header">Account</td>
            <td class="account-detail__table-header">Amount</td>
            <td class="account-detail__table-header">Date and Time</td>
            <td class="account-detail__table-header">Comment</td>
          </tr>
        </thead>
        <tbody>
          {% for item in transfers_to_envelopes|dictsortreversed:"date" %}
            <tr>          
              <td class="account-detail__table-data-transfers">{{ item.account }}</td>
              <td class="account-detail__table-data-transfers">{{ item.amount }}</td>
              <td class="account-detail__table-data-transfers">{{ item.date }}</td>       
              <td class="account-detail__table-data-transfers">{{ item.comment|truncatechars:12 }}</td>    
            </tr>
          {% endfor %}
        {% endif %}      
    </table>
    
    <a href="{% url 'envelope_new_spend' %}" class="button button__home-all">Add New Spend</a>
    <a href="{% url 'envelope_list' %}" class="button button__home-all">View All Envelopes</a>
    
  </div>
  
</section>

{% endblock content %}

templates/envelopes/envelope_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Envelopes{% endblock title %}

{% block style %}{% endblock style %}

{% block content %}

{% if all_accounts|length == 0 %}

<section class="section">
    
  <div class="login__container bd-grid">

    <div class="new__icon-data">
      <h2 class="section-title">My Envelopes</h2>
      <div class="empty__icon">
          <img src="{% static 'art/empty_home.png' %}" alt="" />                
      </div>

      <div class="empty_desc">To get started add new account first</div>
    </div>
            
    <a href="{% url 'account_new' %}" class="button button__home-all">Add New Account</a>
  </div>
</section>

{% elif object_list|length == 0 %}

<section class="section">
    
  <div class="login__container bd-grid">

    <div class="new__icon-data">
      <h2 class="section-title">My Envelopes</h2>
      <div class="empty__icon">
          <img src="{% static 'art/empty_home.png' %}" alt="" />                
      </div>

      <div class="empty_desc">To get started add new envelope</div>
    </div>
            
    <a href="{% url 'envelope_new' %}" class="button button__home-all">Add New Envelope</a>
  </div>
</section>

{% else %}

<section class="section">
  <span class="section-subtitle">My Envelopes</span>
  <h2 class="section-title">{{ total_balance_envelopes }}</h2>
  
  <div class="home__container bd-grid">
    
    {% for envelope in object_list %}

    <a href="{% url 'envelope_detail' envelope.pk %}" class="card">
      <div class="card__left">
        <i class="{{ envelope.icon }} card__icon"></i>
      </div>
      <div class="card__right">
        <div class="card__header">
          <h3 class="card__name">{{ envelope.name }}</h3>         
        </div>
        
        <h3 class="card__balance">{{ envelope.balance }}</h3>

        <div class="card__line"></div>
        <div class="card__last-transaction">
          
        {% if envelope.spend_set.all|length == 0 %}          
          <span class="card__last-transaction-amount">No Spend to display</span>          
        {% else %}
          <span class="card__last-transaction-amount"><i class="fas fa-arrow-alt-circle-down card__last-transaction-icon-down"></i> {{ envelope.spend_set.all.last.amount}}</span>
        {% endif %}
            <span class="card__last-transaction-date">{{ envelope.transaction_set.all.last.date|date:"y M d, H:i:s" }}</span>
        </div>
      </div>
    </a>

    {% endfor %}

  </div>
</section>
{% endif %}

<script>
  document.getElementById('envelopes-nav').classList.add('active');
</script>

{% endblock content %}

templates/envelopes/envelope_new.html
{% extends 'base.html' %}
{% load static %}

{% block title %}New Envelope{% endblock title %}

{% block style %}
{% endblock style %}

{% block content %}

<section class="envelopes section">    
  
    <div class="account__new-container bd-grid">
        <div class="new__icon-data">
            <div class="new__icon">
                <img src="{% static 'art/envelope_icon.png' %}" alt="" />                
            </div>
        </div>
        <h2 class="section-title">New Envelope</h2>
        
        {% if all_accounts|length == 0 %}
            <div class="new__icon-data">
            <div class="empty_desc">To add new envelope add new account first</div>
            </div>
            <a href="{% url 'account_new' %}" class="button button__home-all">Add New Account</a>

        {% else %}

        <form action="" class="account__new-form" method="post">
            {% csrf_token %}

            <!-- {{ form }} -->
            <div class="account__new-inputs">
                <input type="text" name="name" required placeholder="Envelope Name" class="account__new-input">
                <input type="number" name="balance" value="0.00" placeholder="Initial Balance(optional)" class="account__new-input">
                <textarea name="description" cols="0" rows="3" placeholder="Description(optional)" class="account__new-input"></textarea>

                <select name="icon" required class="account__new-input">
                    <option value="" selected>Select an Icon</option>
                        <option value="fas fa-shopping-basket">Groceries</option>
                        <option value="fas fa-coffee">Food and Drinks</option>
                        <option value="fas fa-compact-disc">Entertainment</option>
                        <option value="fas fa-couch">Furniture</option>
                        <option value="fas fa-dice">Sports</option>
                        <option value="fas fa-hospital">Medicine</option>
                        <option value="fas fa-mobile-alt">Mobile Phone</option>
                        <option value="fas fa-store">Shopping</option>
                        <option value="fas fa-tools">Utilities</option>
                        <option value="fas fa-tshirt">Clothes</option>
                        <option value="fas fa-baby-carriage">Baby Care</option>
                        <option value="fas fa-book">Books</option>
                        <option value="fas fa-bus">Transportation</option>
                        <option value="fas fa-box-open">Gifts</option>
                        <option value="fas fa-car">Travel</option>
                        <option value="fas fa-hammer">Tools</option>
                        <option value="fas fa-wifi">Internet</option>
                        <option value="fas fa-car-crash">Insurance</option>
                        <option value="fas fa-water">Water</option>
                        <option value="fas fa-file-invoice">Bills</option>
                        <option value="fas fa-gas-pump">Fuel</option>
                        <option value="far fa-lightbulb">Electricity</option>
                        <option value="fas fa-cannabis">Miscellaneous</option>
                </select>

                <input type="submit" value="Create New Envelope" class="button account__new-button">                          
            </div>            
        </form>
  
    </div>
  </section>
  {% endif %}
  
  <script>
    document.getElementById('envelope-new-nav').classList.add('active');
  </script>

{% endblock content %}

templates/envelopes/envelope_new_spend.html
{% extends 'base.html' %}
{% load static %}

{% block title %}New Spend{% endblock title %}

{% block style %}
{% endblock style %}

{% block content %}

<section class="accounts section">
  
    <div class="account__new-container bd-grid">

      <div class="new__icon-data">
        <div class="new__icon">
            <img src="{% static 'art/spend_icon.png' %}" alt="" />                
        </div>
      </div>
      <h2 class="section-title">New Spend</h2>

      {% if all_envelopes|length == 0 %}
        <div class="new__icon-data">
          <div class="empty_desc">To make a spend add new envelope first</div>
        </div>
        <a href="{% url 'envelope_new' %}" class="button button__home-all">Add New Envelope</a>

      {% else %}

        <form action="" class="account__new-form" method="post">
            {% csrf_token %}
            <div class="account__new-inputs">
                {{ form.envelope }}
                <input type="number" name="amount" required placeholder="Amount" class="account__new-input">
                <textarea name="comment" id="" cols="0" rows="3" placeholder="Comment(optional)" class="account__new-input"></textarea>

                <input type="submit" value="Add New Spend" class="button account__new-button">                          
            </div>            
        </form>
      {% endif %}
    </div>
  </section>
  
  <script>
    document.getElementById('accounts-new-spend-nav').classList.add('active');
  </script>

{% endblock content %}

templates/envelopes/transaction_new.html
{% extends 'base.html' %}
{% load static %}

{% block title %}New Transaction{% endblock title %}

{% block style %}
{% endblock style %}

{% block content %}

<noscript>You need to enable JavaScript to run this app.</noscript>

<div class="flex flex-wrap">
    <div class="w-full">
        <nav class="relative flex flex-wrap items-center justify-between py-3 navbar-expand-lg bg-verdigris shadow-md">
            <div class="container px-4 mx-auto flex flex-wrap items-center justify-between">
                <div class="w-full relative flex justify-start lg:w-auto px-1 lg:static lg:block">
                    <button
                        class="text-white cursor-pointer text-xl leading-none py-1 border border-solid border-transparent rounded bg-transparent block lg:hidden outline-none focus:outline-none"
                        type="button" onclick="toggleNavbar('collapse-navbar')">
                        <i class="fas fa-bars"></i>
                    </button>
                    <a class="text-sm font-bold leading-relaxed inline-block ml-4 mr-4 py-2 whitespace-no-wrap uppercase text-white"
                        href="{% url 'home' %}">
                        Expenses
                    </a>
                    <ul class="list-none ml-auto inline-block mt-1 lg:hidden">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                          <a href="#" onclick="openDropdown(event,'user-dropdown-mobile')" class="flex text-sm rounded-full">
                            <span class="px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75">{{ user.username }}</span><img class="h-8 w-8 rounded-full" src="{{ user.profile_pic.url }}" alt="">
                          </a>
                        </li>
                        {% endif %}
            
                        <div class="hidden bg-white text-base z-50 float-left py-2 list-none text-left rounded shadow-lg mt-1 ml-8"
                          style="min-width: 12rem;" id="user-dropdown-mobile">
                          <a href="{% url 'profile' %}"
                            class="text-sm py-2 px-4 font-normal block w-full whitespace-no-wrap bg-transparent text-gray-800">View
                            Profile</a>
                          <div class="mx-2 h-0 my-2 border border-solid border-gray-200"></div>
                          <a href="{% url 'logout' %}"
                            class="text-sm py-2 px-4 font-normal block w-full whitespace-no-wrap bg-transparent text-gray-800">Logout</a>
                        </div>
                      </ul>
                </div>
                <div class="lg:flex lg:flex-grow items-center hidden" id="collapse-navbar">
                    <ul class="flex flex-col lg:flex-row list-none lg:ml-auto">
                        <li class="nav-item">
                            <a class="px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75"
                                href="{% url 'envelope_list' %}">
                                Envelopes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75"
                                href="{% url 'envelope_new' %}">
                                New Envelope
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75"
                                href="{% url 'transaction_new' %}">
                                New Transaction
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75"
                                href="#">
                                Accounts
                            </a>
                        </li>

                        {% if user.is_authenticated %}
                        <li class="nav-item hidden lg:inline-block">
                            <a href="#" onclick="openDropdown(event,'user-dropdown')" class="flex text-sm rounded-full">
                                <span
                                    class="px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75">{{ user.username }}</span><img
                                    class="h-8 w-8 rounded-full" src="{{ user.profile_pic.url }}" alt="">
                            </a>
                        </li>
                        {% endif %}

                        <div class="hidden bg-white text-base z-50 float-left py-2 list-none text-left rounded shadow-lg mt-1 ml-8"
                            style="min-width: 12rem;" id="user-dropdown">
                            <a href="{% url 'profile' %}"
                                class="text-sm py-2 px-4 font-normal block w-full whitespace-no-wrap bg-transparent text-gray-800">View
                                Profile</a>
                            <div class="mx-2 h-0 my-2 border border-solid border-gray-200"></div>
                            <a href="{% url 'logout' %}"
                                class="text-sm py-2 px-4 font-normal block w-full whitespace-no-wrap bg-transparent text-gray-800">Logout</a>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>

<div class="flex justify-center">
    <div
        class="flex px-6 py-4 relative bg-white rounded-md m-4 mb-6 xl:mb-0 shadow-md justify-center items-center w-full md:w-1/2 lg:w-2/5">

        <div class="flex-auto p-5">
            <div class="flex justify-center">
                <img class="flex mr-2 h-12" src="{% static '/art/transaction_new.png' %}" alt="new envelope" />
                <h4 class="flex text-2xl font-semibold text-center items-center ml-2">Add New Transaction</h4>
            </div>

            <form action="" method="post">
                {% csrf_token %}

                <div class="relative w-full mb-3 mt-4">
                    <label class="block text-gray-700 text-xs font-bold mb-2" for="name">Envelope</label>
                    {{ form.envelope }} 
                </div>
                <div class="relative w-full mb-3">
                    <label class="block text-gray-700 text-xs font-bold mb-2" for="balance">Category</label>
                    {{ form.category }}
                </div>
                <div class="relative w-full mb-3">
                    <label class="block text-gray-700 text-xs font-bold mb-2" for="amount">Amount</label>
                    <input type="number" name="amount" required
                    class="px-3 py-3 placeholder-gray-400 text-gray-700 bg-gray-200 rounded text-sm shadow focus:outline-none focus:shadow-outline w-full"
                    placeholder="Initial Balance"
                    style="transition: all 0.15s ease 0s;">
                </div>
            
                <div class="text-center mt-6">
                    <button class="bg-bittersweet text-white active:bg-gray-700 text-sm font-bold uppercase px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1"
                    type="submit" style="transition: all 0.15s ease 0s;">Add
                    Transaction</button>
                </div>

            </form>
        </div>

    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js" charset="utf-8"></script>
<script type="text/javascript">
    /* Sidebar - Side navigation menu on mobile/responsive mode */
    function toggleNavbar(collapseID) {
        document.getElementById(collapseID).classList.toggle("hidden");        
    }
    /* Function for dropdowns */
    function openDropdown(event, dropdownID) {
        let element = event.target;
        while (element.nodeName !== "A") {
            element = element.parentNode;
        }
        var popper = new Popper(element, document.getElementById(dropdownID), {
            placement: "bottom-end"
        });
        document.getElementById(dropdownID).classList.toggle("hidden");
        document.getElementById(dropdownID).classList.toggle("block");
    }
    (function () {
        /* Add current date to the footer */
        document.getElementById("javascript-date").innerHTML = new Date().getFullYear();
    })();
</script>

{% endblock content %}