api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('accounts/', views.AccountsList.as_view()),
]

expense_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('envelopes/', include('envelopes.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),

    # api urls
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from envelopes.models import Envelope

class Account(models.Model):
    class AccountIcon(models.TextChoices):
        CREDITCARD = 'far fa-credit-card', _('Credit Card')
        SAVINGS = 'fas fa-piggy-bank', _('Savings')
        FIXED = 'fas fa-money-check-alt', _('Fixed')  

    name = models.CharField(max_length=255)
    bank = models.CharField(max_length=255, null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    balance = models.DecimalField(decimal_places=2, max_digits=12, default=0.0)
    icon = models.CharField(
        max_length=50,
        choices=AccountIcon.choices,
    )
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('account_list')

class Deposit(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    date = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=255, null=True, blank=True)
    account = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('account_detail', kwargs={'pk': self.account.pk,})

class TransferToAccount(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    date = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=255, null=True, blank=True)
    account_from = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
        related_name='account_from',
    )
    account_to = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
        related_name='account_to',
    )

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('account_list')

class TransferToEnvelope(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    date = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=255, null=True, blank=True)
    account = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
    )
    envelope = models.ForeignKey(
        Envelope,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('account_list')

envelopes/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

class Envelope(models.Model):
    class EnvelopeIcon(models.TextChoices):
        GROCERIES = 'fas fa-shopping-basket', _('Groceries')
        FOODANDDRINKS = 'fas fa-coffee', _('Food and Drinks')
        ENTERTAINMENT = 'fas fa-compact-disc', _('Entertainment')
        FURNITURE = 'fas fa-couch', _('Furniture')
        # CREDITCARD = 'far fa-credit-card', _('Credit Card')
        SPORTS = 'fas fa-dice', _('Sports')
        MEDICINE = 'fas fa-hospital', _('Medicine')
        MOBILE = 'fas fa-mobile-alt', _('Mobile Phone')
        # SAVINGS = 'fas fa-piggy-bank', _('Savings')
        SHOPPING = 'fas fa-store', _('Shopping')
        UTILITIES = 'fas fa-tools', _('Utilities')
        CLOTHES = 'fas fa-tshirt', _('Clothes')
        BABYCARE = 'fas fa-baby-carriage', _('Baby Care')
        BOOKS = 'fas fa-book', _('Books')
        TRANSPORTATION = 'fas fa-bus', _('Transportation')
        GIFTS = 'fas fa-box-open', _('Gifts')
        TRAVEL = 'fas fa-car', _('Travel')
        TOOLS = 'fas fa-hammer', _('Tools')
        INTERNET = 'fas fa-wifi', _('Internet')
        INSURANCE = 'fas fa-car-crash', _('Insurance')
        WATER = 'fas fa-water', _('Water')
        BILLS = 'fas fa-file-invoice', _('Bills')
        FUEL = 'fas fa-gas-pump', _('Fuel')
        ELECTRICITY = 'far fa-lightbulb', _('Electricity')
        MISCELLANEOUS = 'fas fa-cannabis', _('Miscellaneous')
        

    name = models.CharField(max_length=255)
    balance = models.DecimalField(decimal_places=2, max_digits=8, default=0.0)
    description = models.CharField(max_length=255, null=True, blank=True)
    icon = models.CharField(
        max_length=30,
        choices=EnvelopeIcon.choices,
    )
    owner = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('envelope_list')

class Spend(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits=8)
    date = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=255, null=True, blank=True)
    envelope = models.ForeignKey(
        Envelope,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('envelope_detail', kwargs={'pk': self.envelope.pk,})

class Transaction(models.Model):
    class TransactionCategory(models.TextChoices):
        INCOME = 'IN', _('Income')
        EXPENSE = 'EX', _('Expense')

    amount = models.DecimalField(decimal_places=2, max_digits=8)
    date = models.DateTimeField(auto_now_add=True)
    category = models.CharField(
        max_length=2,
        choices=TransactionCategory.choices,
    )
    envelope = models.ForeignKey(
        Envelope,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('envelope_detail', kwargs={'pk': self.envelope.pk,})

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class ExpenseUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)
    profile_pic = models.ImageField(null=True, blank=True)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About Expenses{% endblock title %}

{% block style %}{% endblock style %}

{% block content %}

<section class="section">
  
    <div class="profile-container bd-grid">

        <div class="profile__data">
            <div class="about__pic">
                <img src="{% static 'art/expenses_logo.png' %}" alt="" />                
            </div>
    
            <h2 class="section-title">Expenses</h2>
            <div class="profile__label">Copyright &copy; <span id="year"></span> Anila Senadheera(ianila)</div>
            <div class="profile__label">licensed under the GNU GPLv3 License</div>
            <div class="profile__label"><a href="https://gitlab.com/ianila/expenses">View Source - Expenses by ianila</a></div>
                
        </div>
          
    </div>
  </section>
  
  <script>
    document.getElementById('about-nav').classList.add('active');

    document.getElementById("year").innerHTML = new Date().getFullYear();
  </script>

{% endblock content %}

templates/base.html
<!-- 
/* Expenses by ianila
 * Copyright (C) 202 Anila Senadheera
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */ -->

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- ===== CSS ===== -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" />

  <title>{% block title %}Expenses{% endblock title %}</title>  
  {% block style %}{% endblock style %}

</head>
<body>

  <!--===== HEADER =====-->
    <header class="l-header">
      <nav class="nav bd-grid">
          <div class="nav__toggle" id="nav-toggle">
              <i class="fas fa-bars"></i>
          </div>

          <div class="nav__title-bar">
              <a href="{% url 'home' %}" class="nav__logo">Expenses <box-icon name='palette'></box-icon></a>
          </div>

          <div class="nav__menu" id="nav-menu">
              <div class="nav__close" id="nav-close">
                <i class="fas fa-times"></i>
              </div>

              <a href="{% url 'profile' %}" class="user__container">
                <div class="user__image-container">
                  <img src="{{ user.profile_pic.url }}" alt="">
                </div>
                <h2 class="user__title">{{ user.username }}</h2>
              </a>

              <div class="nav__line"></div>

              <ul class="nav__list">
                  <li class="nav__item"><a href="{% url 'home' %}" class="nav__link" id="home-nav">Home</a></li>
                  
                  <li class="nav__item"><a href="{% url 'account_list' %}" class="nav__link" id="accounts-nav">Accounts</a></li>
                  <li class="nav__item"><a href="{% url 'account_new' %}" class="nav__link nav__link-sub" id="account-new-nav">New Account</a></li>
                  <li class="nav__item"><a href="{% url 'account_new_deposit' %}" class="nav__link nav__link-sub" id="accounts-new-deposit-nav">New Deposit</a></li>
                  <li class="nav__item"><a href="{% url 'account_new_account_transfer' %}" class="nav__link nav__link-sub" id="accounts-new-tranfer-account-nav">Transfer to Account</a></li>
                  <li class="nav__item"><a href="{% url 'account_new_envelope_transfer' %}" class="nav__link nav__link-sub" id="accounts-new-tranfer-envelope-nav">Transfer to Envelope</a></li>
              </ul>

              <div class="nav__line"></div>

              <ul class="nav__list">
                  <li class="nav__item"><a href="{% url 'envelope_list' %}" class="nav__link" id="envelopes-nav">Envelopes</a></li>
                  <li class="nav__item"><a href="{% url 'envelope_new' %}" class="nav__link nav__link-sub" id="envelope-new-nav">New Envelope</a></li>
                  <li class="nav__item"><a href="{% url 'envelope_new_spend' %}" class="nav__link nav__link-sub" id="accounts-new-spend-nav">Spend</a></li>
              </ul>

              <div class="nav__line"></div>
              
              <ul class="nav__list">
                <li class="nav__item"><a href="{% url 'profile' %}" class="nav__link" id="profile-nav">Profile</a></li>
                <li class="nav__item"><a href="{% url 'about' %}" class="nav__link" id="about-nav">About</a></li>
                <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link">Logout</a></li>
              </ul>
          </div>
      </nav>
    </header>

    <script src="{% static 'js/expenses.js' %}"></script>

    {% block content %}
    {% endblock content %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if latest_accounts|length == 0 %}

<section class="section">
    
  <div class="login__container bd-grid">

    <div class="new__icon-data">
      <h2 class="section-title">Welcome to Expenses</h2>
      <span class="section-subtitle">fastest way to manage your expenses</span>
      <div class="empty__icon">
          <img src="{% static 'art/empty_home.png' %}" alt="" />                
      </div>

      <div class="empty_desc">To get started add new account</div>
    </div>
            
    <a href="{% url 'account_new' %}" class="button button__home-all">Add New Account</a>
  </div>
</section>

{% else %}

<section class="section">
  
  <span class="section-subtitle">My Accounts</span>
  <h2 class="section-title">{{ total_balance_accounts }}</h2>
  
  <div class="home__container bd-grid">
    
    {% for account in latest_accounts %}

    <a href="{% url 'account_detail' account.pk %}" class="card">
      <div class="card__left">
        <i class="{{ account.icon }} card__icon"></i>
      </div>
      <div class="card__right">
        <div class="card__header">
          <h3 class="card__name">{{ account.name }}</h3>
          <span class="card__sub-name">{{ account.bank }}</span>          
        </div>
        
        <h3 class="card__balance">{{ account.balance }}</h3>

        <div class="card__line"></div>
        <div class="card__last-transaction">
          
          {% if account.deposit_set.all|length == 0 %}          
            <span class="card__last-transaction-amount">No Transaction to display</span>          
          {% else %}
            <span class="card__last-transaction-amount"><i class="fas fa-arrow-alt-circle-up card__last-transaction-icon"></i> {{ account.deposit_set.all.last.amount}}</span>
          {% endif %}
            <span class="card__last-transaction-date">{{ account.deposit_set.all.last.date|date:"y M d, H:i:s" }}</span>
        </div>
      </div>
    </a>

    {% endfor %}

    <a href="{% url 'account_list' %}" class="button button__home-all">View All Accounts</a>
  </div>  
</section>

<div class="section__line"></div>

<section class="section">
  <span class="section-subtitle">My Envelopes</span>
  <h2 class="section-title">{{ total_balance_envelopes }}</h2>
  
  <div class="home__container bd-grid">
    
    {% for envelope in latest_envelopes %}

    <a href="{% url 'envelope_detail' envelope.pk %}" class="card">
      <div class="card__left">
        <i class="{{ envelope.icon }} card__icon"></i>
      </div>
      <div class="card__right">
        <div class="card__header">
          <h3 class="card__name">{{ envelope.name }}</h3>         
        </div>
        
        <h3 class="card__balance">{{ envelope.balance }}</h3>

        <div class="card__line"></div>
        <div class="card__last-transaction">
          
          {% if envelope.spend_set.all|length == 0 %}          
            <span class="card__last-transaction-amount">No Spend to display</span>          
          {% else %}
            <span class="card__last-transaction-amount"><i class="fas fa-arrow-alt-circle-down card__last-transaction-icon-down"></i> {{ envelope.spend_set.all.last.amount}}</span>
          {% endif %}
            <span class="card__last-transaction-date">{{ envelope.spend_set.all.last.date|date:"y M d, H:i:s" }}</span>
        </div>
      </div>
    </a>

    {% endfor %}

    <a href="{% url 'envelope_list' %}" class="button button__home-all">View All Envelopes</a>
  </div>
</section>

{% endif %}
<script>
  document.getElementById('home-nav').classList.add('active');
</script>

{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Profile{% endblock title %}

{% block style %}{% endblock style %}

{% block content %}

<section class="section">
  
    <div class="profile-container bd-grid">

        <div class="profile__data">
            <div class="profile__pic">
                <img src="{{ user.profile_pic.url }}" alt="" />                
            </div>
    
            <h2 class="section-title">{{ user.username }}</h2>
            <div class="profile__inputs">
                <div class="profile__label">Joined</div>
                <div class="account__new-input">{{ user.date_joined }}</div>

                <div class="profile__label">Last Login</div>
                <div class="account__new-input">{{ user.last_login }}</div>                                         
            </div> 
        </div>
          
    </div>
  </section>
  
  <script>
    document.getElementById('profile-nav').classList.add('active');
  </script>

{% endblock content %}

templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- ===== CSS ===== -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" />

  <title>Signup to Expenses</title>  
</head>
<body>

<section class="login section">
  
  <div class="login__container bd-grid">

    <div class="profile__data">
      <div class="about__pic">
          <img src="{% static 'art/expenses_logo.png' %}" alt="" />                
      </div>          
    </div>

    <h2 class="section-title">Signup to Expenses</h2>

      <form action="" class="account__new-form" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="account__new-inputs">
              <input type="text" name="username" required placeholder="Username" class="account__new-input">
              <input type="password" name="password1" required placeholder="Password" class="account__new-input">
              <input type="password" name="password2" required placeholder="Password Confirmation" class="account__new-input">
              
              <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic" class="account__new-input" hidden="hidden"/>
              
              <div>
                <button type="button" class="profile__picture-button" id="upload-button"><i class="fas fa-upload"></i> &nbsp; Upload Profile Picture</button>
              </div>
              
              <input type="submit" value="Signup to Expenses" class="button account__new-button">                          
          </div>
      </form>

      <div class="login__line"></div>
      
      <a href="{% url 'login' %}" class="button button__home-all">Already have an account? Login</a>
  </div>
</section>

<script>
  const fileButton = document.getElementById("id_profile_pic");
  const uploadButton = document.getElementById("upload-button");
  const uploadLabel = document.getElementById("upload-label");

  uploadButton.addEventListener("click", function() {
    fileButton.click();
  });

  fileButton.addEventListener("change", function () {
    if(fileButton.value) {
      uploadButton.innerHTML = fileButton.value.match(/[\/\\]([\w\d\s\.\-\(\)]+)$/)[1] + '&nbsp; <i class="fas fa-check-circle"></i>';
    } else {
      uploadButton.innerHTML = "<i class='fas fa-upload'></i> &nbsp; Upload Profile Picture";
    }
  });

</script>
</body>
</html>